apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-data-mdb-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/mysql/datadir-0/
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-data-mdb-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/mysql/datadir-1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-data-mdb-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/mysql/datadir-2/
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-data-mdb-3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/mysql/datadir-3/

