---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  externalIPs:
   - 167.99.92.225
  ports:
  - port: 80
    name: wordpress
  selector:
    app: wordpress
---

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wp-volume
        env:
          - name: WORDPRESS_DB_PASSWORD
            value: t4t5um4k1
          - name: WORDPRESS_DB_USER
            value: wpuser
          - name: WORDPRESS_DB_NAME
            value: wp-db-data
          - name: WORDPRESS_DB_HOST
            value: wp-db-cluster-pxc.default.svc.cluster.local
      volumes:
        - name: "wp-volume"
          hostPath:
            path: "/mnt/web/data"

